FileVersion = 1
Dependencies = {corlib = "*", ari_core = "*", ari_io = "*"}

[Project]
Name = "ari_en"
TargetType = "BeefLib"
StartupObject = "ari_en.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/../dist/win64/Debug/cari_en.lib", "$(ProjectDir)/../dist/win64/Debug/ari_en.lib", "$(ProjectDir)/../dist/win64/Debug/yojimbo.lib", "$(ProjectDir)/../dist/win64/Debug/mbedcrypto.lib", "$(ProjectDir)/../dist/win64/Debug/mbedtls.lib", "$(ProjectDir)/../dist/win64/Debug/mbedx509.lib", "$(ProjectDir)/../dist/win64/Debug/sodium.lib"]

[[ProjectFolder.Items]]
Type = "Source"
Path = "../src/en/AriSystem.bf"

[[ProjectFolder.Items]]
Type = "Source"
Path = "../src/en/Entity.bf"

[[ProjectFolder.Items]]
Type = "Source"
Path = "../src/en/Node.bf"

[[ProjectFolder.Items]]
Type = "Source"
Path = "../src/en/World.bf"
