FileVersion = 1
Projects = {Ariyana_beef = {Path = "."}, t01Init = {Path = "tests/t01Init"}, t02Network = {Path = "tests/t02Network"}, t02NetworkClient = {Path = "tests/t02NetworkClient"}, CurlBeef = {Path = "deps/CurlBeef"}, BeefExtensionsLib = {Path = "deps/Beef-Extensions-Lib"}, JSON_Beef = {Path = "deps/JSON_Beef/lib"}, ari_core = {Path = "ari_core"}, test_core = {Path = "test_core"}, ari_2d = {Path = "ari_2d"}, ari_gfx = {Path = "ari_gfx"}, ari_en = {Path = "ari_en"}, ari_io = {Path = "ari_io"}, ari_net = {Path = "ari_net"}, ari_gui = {Path = "ari_gui"}, ari_3d = {Path = "ari_3d"}, ari_net_3d = {Path = "ari_net_3d"}}
ExtraPlatforms = ["armv7-none-linux-android21"]

[Workspace]
StartupProject = "test_core"
