FileVersion = 1
Dependencies = {corlib = "*", ari_en = "*", CurlBeef = "*"}

[Project]
Name = "ari_net"
TargetType = "BeefLib"
StartupObject = "ari_net.Program"
DefaultNamespace = "ari.net"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/../dist/win64/Debug/cari_net.lib", "$(ProjectDir)/../dist/win64/Debug/ari_net.lib"]

[[ProjectFolder.Items]]
Type = "Source"
Path = "../src/net/ClientSystem.bf"

[[ProjectFolder.Items]]
Type = "Source"
Path = "../src/net/HttpClientService.bf"

[[ProjectFolder.Items]]
Type = "Source"
Path = "../src/net/HttpRequest.bf"

[[ProjectFolder.Items]]
Type = "Source"
Path = "../src/net/HttpResponse.bf"

[[ProjectFolder.Items]]
Type = "Source"
Path = "../src/net/Net.bf"

[[ProjectFolder.Items]]
Type = "Source"
Path = "../src/net/NetSerializer.bf"

[[ProjectFolder.Items]]
Type = "Source"
Path = "../src/net/NetworkSystem.bf"

[[ProjectFolder.Items]]
Type = "Source"
Path = "../src/net/PropertyReplicator.bf"

[[ProjectFolder.Items]]
Type = "Source"
Path = "../src/net/RPC.bf"

[[ProjectFolder.Items]]
Type = "Source"
Path = "../src/net/ServerSystem.bf"
