FileVersion = 1
Dependencies = {corlib = "*", ari_net = "*"}

[Project]
Name = "ari_biz"
TargetType = "BeefLib"
StartupObject = "ari_biz.Program"

[[ProjectFolder.Items]]
Type = "Source"
Path = "../src/biz/GoogleAnalytics.bf"
