FileVersion = 1
Dependencies = {corlib = "*", ari_core = "*"}

[Project]
Name = "ari_io"
TargetType = "BeefLib"
StartupObject = "ari_io.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/../dist/win64/Debug/cari_io.lib", "$(ProjectDir)/../dist/win64/Debug/ari_io.lib", "$(ProjectDir)/../dist/win64/Debug/ari_fs_local.lib"]

[[ProjectFolder.Items]]
Type = "Source"
Path = "../src/io/FileSystemBase.bf"

[[ProjectFolder.Items]]
Type = "Source"
Path = "../src/io/FileSystemLocal.bf"

[[ProjectFolder.Items]]
Type = "Source"
Path = "../src/io/Io.bf"

[[ProjectFolder.Items]]
Type = "Source"
Path = "../src/io/IoEvents.bf"

[[ProjectFolder.Items]]
Type = "Source"
Path = "../src/io/Zip.bf"
